#!/usr/bin/with-contenv sh

STARTCMD="su-exec daspanel:daspanel /usr/sbin/caddy --conf=/etc/caddy/caddyfile --log=stdout"

[[ -z "${CADDY_AGREE}" ]] && CADDY_AGREE="true"
[[ -z "${CADDY_CA}" ]] && CADDY_CA="https://acme-v01.api.letsencrypt.org/directory"
[[ -z "${CADDY_CPU}" ]] && CADDY_CPU="100%"
[[ -z "${CADDY_EMAIL}" ]] && CADDY_EMAIL="$DASPANEL_ACME_EMAIL"
[[ -z "${CADDY_GRACE}" ]] && CADDY_GRACE="5s"
[[ -z "${CADDY_HTTP2}" ]] && CADDY_HTTP2="true"
[[ -z "${CADDY_QUIET}" ]] && CADDY_QUIET="false"

[[ -n "${CADDY_AGREE}" ]] && STARTCMD="${STARTCMD} -agree=${CADDY_AGREE}"
[[ -n "${CADDY_CA}" ]] && STARTCMD="${STARTCMD} -ca=${CADDY_CA}"
[[ -n "${CADDY_CPU}" ]] && STARTCMD="${STARTCMD} -cpu=${CADDY_CPU}"
[[ -n "${CADDY_EMAIL}" ]] && STARTCMD="${STARTCMD} -email=${CADDY_EMAIL}"
[[ -n "${CADDY_GRACE}" ]] && STARTCMD="${STARTCMD} -grace=${CADDY_GRACE}"
[[ -n "${CADDY_HTTP2}" ]] && STARTCMD="${STARTCMD} -http2=${CADDY_HTTP2}"
[[ -n "${CADDY_QUIET}" ]] && STARTCMD="${STARTCMD} -quiet=${CADDY_QUIET}"

exec ${STARTCMD}
